env:
  node: true
  es2021: true
  jest: true

extends: 
  - airbnb-base
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - jest

rules: 
  import/extensions: off
  